### ISSUE TITLE
NLU_ENV_CONFIG_PATH

### ISSUE THREAD

**Issue by cbaziotis** [zphang/usc_dae#2]
This is just an FYI.
The project requires the environment variable `NLU_ENV_CONFIG_PATH` even though it is not mentioned in the README. For others reading this issue, just add the variable by pointing to `env_configs/env_config.json`
```
export NLU_ENV_CONFIG_PATH="/my_workspace_path/usc_dae/env_configs/env_config.json"
```

**Comment by Iwontbecreative** [comment]
Thanks for reporting this, adressed in the README!
